-- Typed copy of staging.coaching_staff: every column, same names, types fixed. Generated by
-- scripts/gen_clean_models.py; edit the rules there rather than this file.
-- the source key is not unique for every row: keep the latest copy of each _row_id
select distinct on (_row_id)
    md5(concat_ws('|', coalesce(season::text, ''), coalesce(team::text, ''), coalesce(role::text, ''), coalesce(coach::text, ''), coalesce(start_date::text, ''))) as _row_id,
    season::smallint                               as season,
    team,
    role,
    title,
    coach,
    is_interim,
    start_date,
    end_date,
    note,
    flags,
    source_url,
    _loaded_at
from {{ source('staging', 'coaching_staff') }}
where true
{{ only_new('_loaded_at') }}
order by _row_id, _loaded_at desc
