-- Typed copy of staging.depth_charts: every column, same names, types fixed. Generated by
-- scripts/gen_clean_models.py; edit the rules there rather than this file.
-- the source key is not unique for every row: keep the latest copy of each _row_id
select distinct on (_row_id)
    md5(concat_ws('|', coalesce(season::text, ''), coalesce(club_code::text, ''), coalesce(week::text, ''), coalesce(game_type::text, ''), coalesce(depth_team::text, ''), coalesce(last_name::text, ''), coalesce(first_name::text, ''), coalesce(football_name::text, ''), coalesce(formation::text, ''), coalesce(gsis_id::text, ''), coalesce(jersey_number::text, ''), coalesce(position::text, ''), coalesce(elias_id::text, ''), coalesce(depth_position::text, ''), coalesce(full_name::text, ''), coalesce(dt::text, ''), coalesce(team::text, ''), coalesce(player_name::text, ''), coalesce(espn_id::text, ''), coalesce(pos_grp_id::text, ''), coalesce(pos_grp::text, ''), coalesce(pos_id::text, ''), coalesce(pos_name::text, ''), coalesce(pos_abb::text, ''), coalesce(pos_slot::text, ''), coalesce(pos_rank::text, ''))) as _row_id,
    season::smallint                               as season,
    club_code,
    week::smallint                                 as week,
    game_type,
    depth_team,
    last_name,
    first_name,
    football_name,
    formation,
    gsis_id,
    jersey_number,
    position,
    elias_id,
    depth_position,
    full_name,
    _loaded_at,
    dt::timestamptz                                as dt,
    team,
    player_name,
    espn_id,
    pos_grp_id,
    pos_grp,
    pos_id,
    pos_name,
    pos_abb,
    pos_slot::smallint                             as pos_slot,
    pos_rank::smallint                             as pos_rank
from {{ source('staging', 'depth_charts') }}
where true
{{ only_new('_loaded_at') }}
order by _row_id, _loaded_at desc
