-- Typed copy of staging.participation: every column, same names, types fixed. Generated by
-- scripts/gen_clean_models.py; edit the rules there rather than this file.
select
    nflverse_game_id,
    old_game_id,
    play_id::integer                               as play_id,
    possession_team,
    offense_formation,
    offense_personnel,
    defenders_in_box::smallint                     as defenders_in_box,
    defense_personnel,
    number_of_pass_rushers::smallint               as number_of_pass_rushers,
    players_on_play,
    offense_players,
    defense_players,
    n_offense::smallint                            as n_offense,
    n_defense::smallint                            as n_defense,
    ngs_air_yards,
    time_to_throw,
    was_pressure,
    route,
    defense_man_zone_type,
    defense_coverage_type,
    offense_names,
    defense_names,
    offense_positions,
    defense_positions,
    offense_numbers,
    defense_numbers,
    _loaded_at,
    season::smallint                               as season
from {{ source('staging', 'participation') }}
where true
{{ only_new('_loaded_at') }}
