-- Typed copy of staging.rosters: every column, same names, types fixed. Generated by
-- scripts/gen_clean_models.py; edit the rules there rather than this file.
-- the source key is not unique for every row: keep the latest copy of each _row_id
select distinct on (_row_id)
    md5(concat_ws('|', coalesce(season::text, ''), coalesce(team::text, ''), coalesce(position::text, ''), coalesce(depth_chart_position::text, ''), coalesce(jersey_number::text, ''), coalesce(status::text, ''), coalesce(full_name::text, ''), coalesce(first_name::text, ''), coalesce(last_name::text, ''), coalesce(birth_date::text, ''), coalesce(height::text, ''), coalesce(weight::text, ''), coalesce(college::text, ''), coalesce(gsis_id::text, ''), coalesce(espn_id::text, ''), coalesce(sportradar_id::text, ''), coalesce(yahoo_id::text, ''), coalesce(rotowire_id::text, ''), coalesce(pff_id::text, ''), coalesce(pfr_id::text, ''), coalesce(fantasy_data_id::text, ''), coalesce(sleeper_id::text, ''), coalesce(years_exp::text, ''), coalesce(headshot_url::text, ''), coalesce(ngs_position::text, ''), coalesce(week::text, ''), coalesce(game_type::text, ''), coalesce(status_description_abbr::text, ''), coalesce(football_name::text, ''), coalesce(esb_id::text, ''), coalesce(gsis_it_id::text, ''), coalesce(smart_id::text, ''), coalesce(entry_year::text, ''), coalesce(rookie_year::text, ''), coalesce(draft_club::text, ''), coalesce(draft_number::text, ''))) as _row_id,
    season::smallint                               as season,
    team,
    position,
    depth_chart_position,
    jersey_number,
    status,
    full_name,
    first_name,
    last_name,
    birth_date,
    height::smallint                               as height,
    weight::smallint                               as weight,
    college,
    gsis_id,
    espn_id,
    sportradar_id,
    yahoo_id,
    rotowire_id,
    pff_id,
    pfr_id,
    fantasy_data_id,
    sleeper_id,
    years_exp::smallint                            as years_exp,
    headshot_url,
    ngs_position,
    week::smallint                                 as week,
    game_type,
    status_description_abbr,
    football_name,
    esb_id,
    gsis_it_id,
    smart_id,
    entry_year::smallint                           as entry_year,
    rookie_year::smallint                          as rookie_year,
    draft_club,
    draft_number,
    _loaded_at
from {{ source('staging', 'rosters') }}
where true
{{ only_new('_loaded_at') }}
order by _row_id, _loaded_at desc
