-- Typed copy of staging.officials: every column, same names, types fixed. Generated by
-- scripts/gen_clean_models.py; edit the rules there rather than this file.
select
    game_id,
    game_key,
    official_name,
    position,
    jersey_number::smallint                        as jersey_number,
    official_id,
    season::smallint                               as season,
    season_type,
    week::smallint                                 as week,
    _loaded_at
from {{ source('staging', 'officials') }}
where true
{{ only_new('_loaded_at') }}
