-- Typed copy of staging.teams: every column, same names, types fixed. Generated by
-- scripts/gen_clean_models.py; edit the rules there rather than this file.
select
    team_abbr,
    team_name,
    team_id,
    team_nick,
    team_conf,
    team_division,
    team_color,
    team_color2,
    team_color3,
    team_color4,
    team_logo_wikipedia,
    team_logo_espn,
    team_wordmark,
    team_conference_logo,
    team_league_logo,
    team_logo_squared,
    _loaded_at
from {{ source('staging', 'teams') }}
where true
{{ only_new('_loaded_at') }}
